name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test -- --json --outputFile=result.json --testLocationInResults
      - uses: reviewdog/action-eslint@v1
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: tanmen/jest-reporter@v1
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
